CREATE TABLE USER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE SAVEDSONGS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INSTRUMENT VARCHAR(255) NOT NULL,
    SONGMAP LONGTEXT NOT NULL,
    EMAIL VARCHAR(255) REFERENCES USER(EMAIL)
);

INSERT INTO USER VALUES(1, 'CRESCENDO', '70hncs@gmail.com','papajon');
INSERT INTO USER VALUES(2, 'XELTYX', 'looperloshamannoob@gmail.com', 'erikolim');
INSERT INTO USER VALUES(3, 'HAO', 'kevinrennzx@gmail.com', 'pucongwei');
INSERT INTO USER VALUES(4, 'XTERMINATION', 'russelchandra.rc@gmail.com', 'panikga');